name: AI News Aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-news-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --no-dev --frozen

      - run: uv run python -m app.main
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
